### ISSUE TITLE
Does not work on Redmine 3.4.2

### ISSUE THREAD

**Issue by x-itec** [centosadmin/redmine_agreement#1]
After install + setup whatever I try register or login or whatever this plugin does not work, it does simply nothing currently.

RM 3.4.2 stable

**Comment by constXife** [comment]
Hi, @x-itec! Sorry for long response. It look's like a bug. I fixed it, try to update your plugin from this repository.

**Comment by constXife** [comment]
I'm closing issue. If you will catch any error - create a new issue. Thanks!
