### ISSUE TITLE
Filter chain halted as :check_agreement rendered or redirected

### ISSUE THREAD

**Issue by abrackman** [centosadmin/redmine_agreement#2]
New users are redirected to the agreement page, however clicking the agree/reject buttons results in a Not Found error: "The requested URL /agreements/accept was not found on this server."

Production log shows "Filter chain halted as :check_agreement rendered or redirected"

Do you have any guidance on how I might be able to resolve this?

**Comment by olemskoi** [comment]
Did you set up plugin at administration - modules - parameters page?

**Comment by abrackman** [comment]
I set it up at administration->plugins->redmine_agreement->configure.  Running Redmine 3.4.4, ran the rake successfully after installing.

The full paths to the individual Wiki pages with the accept & reject are "/redmine/projects/redmine/wiki/Accept" & "/redmine/projects/redmine/wiki/Reject" but using those paths for the buttons results in endless redirects to the terms of use page.  Seems like this might be the right direction to go in, but like its not updating the user table.

Even clicking sign out does nothing in that situation, and checking the production log shows the "Filter chain halted as :check_agreement rendered or redirected"

**Comment by vladislav-yashin** [comment]
Can you post a part of your agreement wiki page with accept/reject links?

**Comment by abrackman** [comment]
> 5. Disclaimer of Liability

>IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

>6. No Endorsement

>Neither the name of ______, nor the names of its contributors may be used to endorse or promote products derived from this Program without specific prior written permission.

>"Accept":/agreements/accept | "Reject":/agreements/reject

Here is the bottom of the wiki page with both links using the button format from the README.  

We've created wiki pages for the agreement and for the rejection ("/redmine/projects/redmine/wiki/Accept" & "/redmine/projects/redmine/wiki/Reject", but replacing the button paths with these just results in the endless redirects.

These wiki pages are part of a generic project named "Redmine" right now, but there will be several projects on this Redmine install in the long run and we need to get it set up so that new users for any project must accept the agreement.

**Comment by olemskoi** [comment]
What is full URL to redmine Wiki page?

**Comment by abrackman** [comment]
Actually, just got it to work!  The button paths for our installation needed to be "/redmine/agreements/accept" and "/redmine/agreements/reject" (maybe this has to do with the directory structure created by the Bitnami installer).  Should've tried that...

The issue we must address now though is that since we will have several projects, it seems like the accept/reject wiki pages will need to be created inside each individual project unless it is left in a public project of it's own?  There does not seem to be another way to use the agreement globally?

**Comment by olemskoi** [comment]
There is one global agreement for all users and no other functionality.

**Comment by abrackman** [comment]
Right - however wiki pages must exist within a public project in order to actually be accessible to a user. If the final install includes Project A, Project B, and Project C (with the same agreement necessary for all three) - then the accept/reject Wiki pages must themselves be either within one of those three projects or in a separate public project of their own, right?  Just want to be sure I understand the functionality - thanks for the help!

**Comment by olemskoi** [comment]
You need only one project (project named "Redmine" as you described) with wiki pages /redmine/agreements/accept and /redmine/agreements/reject. And all users need access to these pages. The easiest way to give access - make project public. But you can add users to this project by hand - in this way there is no need to make it public.

**Comment by abrackman** [comment]
Got it - thanks again for the assistance!
